#!/bin/bash

$ mkdir _posts
$ cd _posts
$ touch 2019-04-13-first-post.md
$ vi 2021-08-10-first-post.md
---
title:  "Github 블로그 시작하기"
excerpt: "GitHub 블로그를 시작하기로 했다."

categories:
  - Blog
tags:
  - Blog
last_modified_at: 2021-08-10T08:06:00-05:00
--

github 블로그를 처음으로 시작하게 되었다. 

#!/bin/bash

$ git add .
$ git commit -m "첫번째 블로그 글 등록"
$ git push -u origin master
